apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.order.name }}
  labels:
    {{- include "ssu-commerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "order-server.selectorLabels" . | nindent 4 }}
  containers:
    - env:
      - name: SPRING_PROFILES_ACTIVE
        value: prod
