apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
  labels:
    {{- include "ssu-commerce.labels" . | nindent 4 }}
  annotations:
    {{- include "ssu-commerce.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.pod.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "front-server.selectorLabels" . | nindent 4 }}
