apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.book.name }}
  labels:
    {{- include "ssu-commerce.labels" . | nindent 4 }}
  annotations:
    {{- include "ssu-commerce.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.book.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "book-server.selectorLabels" . | nindent 4 }}
