# Default values for ssu-commerce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
active: dev
gateway:
  name: ssu-commerce-gateway-server
  image:
    repository: ghcr.io/ssu-commerce/gateway
    tag: 2024.09.7
  pod:
    port: 8080
  service:
    port: 8080
book:
  name: ssu-commerce-book-server
  image:
    repository: ghcr.io/ssu-commerce/book-server/api
    tag: "2024.07.111"
  pod:
    port: 8080
  service:
    port: 8080
  replicaCount: 1
order:
  name: ssu-commerce-order-server
  image:
    repository: ghcr.io/ssu-commerce/order-server/api
    tag: 2024.03.4
  pod:
    port: 8080
  service:
    port: 8080
  replicaCount: 1
config:
  name: ssu-commerce-config-server
  image:
    repository: ghcr.io/ssu-commerce/ssu-commerce-config-server
    tag: 2024.06.11
  pod:
    port: 8080
  service:
    port: 8080
account:
  name: ssu-commerce-account-server
  image:
    repository: ghcr.io/ssu-commerce/account/api
    tag: 2024.09.5
  pod:
    port: 8080
  service:
    port: 8080
image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets: [{name: dockerconfigjson-github-com}]
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: LoadBalancer
  port: 80
  loadBalancer:
    type: "nlb"
    size: "SMALL"
ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
